### ISSUE TITLE
Unable to Attach Documents Since Upgrading to v1.0.26

### ISSUE THREAD

**Issue by PIMJIM** [fguillot/kanboard#1979] opened 2016-03-08 22:35 UTC
### Expected behaviour

Tell us what should happen:
I should be able to drag and drop or browse to an attachment and add it to a task.

### Actual behaviour

Tell us what happens instead:
Since upgrading to v1.0.26 yesterday, we can no longer attach a document to a task using either method. The progress bar never moves past 0%. We have tried this using IE 10, IE 11 and latest version of Firefox.

### Steps to reproduce

1.Click on a task
2. From the Actions Menu, select the Attach a document item
3. Browse to a file or drag the file and drop it on the drop area

### Configuration

- Kanboard version:v1.0.26
- Database type and version: MYSQL 14.14 Distrib 5.5.47 (using mysql -V command)
- PHP version: 5.5.9-1ubuntu4.14 (using php -v command)
- OS: Windows 7 x64
- Browser: IE 10, IE 11 and latest version of Firefox

**Comment by PIMJIM** [comment] 2016-03-09 19:57
I'm not sure why but I tried turning on debugging to see if I can get more info and I got an error that the log file could not be created. I re-ran the command sudo chown -R www-data:www-data kanboard/data and I was able to start up KB with debugging and now I can also attach documents but the progress bar for the uploads does not work on either browser that i try.

**Comment by HenLab** [comment] 2016-03-18 18:29
Fix?

**Comment by stevensanpj** [comment] 2016-03-22 11:47
I have the same problem as described by PIMJIM.  
Is there a work around for this?

**Comment by hblunck** [comment] 2016-03-22 14:53
Same problem here with v1.0.26 on a SUSE Linux Server, using up-to-date Firefox.
`data` directory is accessible, since the tool can access the sqlite database and also write debug files.
There seem to be no related entries in the debug file.
* PHP: 5.3.17
* Apache 2.2.29
* Database: sqlite
* Browser: Firefox 45.0.1

**Comment by Busfreak** [comment] 2016-03-22 15:40
Same here, after update from 1.0.26 to current nightly build, screenshots are not shown anymore.
Files are stored in data directory, but the src in the image tag ist not accessable:
`<img src="/kanboard/?controller=FileViewer&amp;action=image&amp;file_id=13&amp;project_id=1&amp;task_id=5" alt="Screenshot aufgenommen 03/22/2016 15:27 .png">`

"the graphic 'xxx' can not be displayed because it contains errors"

Configuration

    Version: master
    PHP version: 5.3.10-1ubuntu3.21
    PHP SAPI: apache2handler
    OS version: Linux 3.2.0-97-generic-pae
    Datenbanktreiber mysql
    Database version: 5.5.46-0ubuntu0.12.04.2
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by Busfreak** [comment] 2016-03-22 16:59
OK, I found the reason, but not the problem.
For me, the problem is associated with a plugin.
I cancel this issue for me.
THX

**Comment by stevensanpj** [comment] 2016-03-22 17:03
Which plugin Busfreak?  I removed all of mine and still have the problem...

**Comment by Busfreak** [comment] 2016-03-22 17:44
an experimental plugin, see above...

**Comment by soshallapps** [comment] 2016-04-13 17:25
Hi

Have same problem with latest version on Windows  x64bit OS. 
Have no plugins installed.
Please provide a workaround/solution.   

Regards,
Bhavik

**Comment by pugst3r** [comment] 2016-04-22 10:38
cannot upload file either. No plugins installed.  It was working fine before the upgrade.

**Comment by fguillot** [comment] 2016-06-07 02:08
Do you guys still having the issue with a more recent version of Kanboard?

**Comment by stevensanpj** [comment] 2016-06-07 06:10
Working for me now.

**Comment by fguillot** [comment] 2016-06-07 13:31
Ok, so I close this issue. If you have a problem open a new ticket.

**Closed by fguillot** 2016-06-07 13:31 UTC
Labels: unable to reproduce bug

**Comment by billkindle** [comment] 2016-08-13 19:36
I'm seeing this same problem even when choosing save. 

Application version: 1.0.32
PHP version: 5.4.16
PHP SAPI: apache2handler
OS version: Linux 3.10.0-327.22.2.el7.x86_64
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

At first I thought maybe it was a browser issue, but I could not get this feature to work with either screenshots or files. Upload functionality appears to be broken.
