### ISSUE TITLE
HTML Hyperlink/URL helper

### ISSUE THREAD

**Issue by Kolesar** [fguillot/kanboard#2054] opened 2016-03-27 11:01 UTC
### Expected behaviour

Sorting task comments

### Actual behaviour

When click on sorting comments inside task get ``Internal Error: Action not implemented`` because inside URL Helper class method ``href`` put ``&amp;`` instead only ``&``.
When open web page to see what is the inside HTML code detect that ALL links have ``&amp;`` instead ``&``, like

```
    <body data-status-url="/kanboard/?controller=app&amp;action=status"
          data-login-url="/kanboard/?controller=auth&amp;action=login"
          data-markdown-preview-url="/kanboard/?controller=TaskHelper&amp;action=preview"
          data-keyboard-shortcut-url="/kanboard/?controller=Doc&amp;action=shortcuts"
          data-timezone="UTC"
          data-js-lang="en">
```

It is normal behaviour or what?

### Steps to reproduce

1. Open task
2. Add few comments
3. Try to sort comments

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

    Verzija aplikacije: master
    PHP version: 5.6.11-1ubuntu3.1
    PHP SAPI: apache2handler
    OS version: Linux 4.2.0-34-generic
    Database driver: mysql
    Database version: 5.6.28-0ubuntu0.15.10.1
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by fguillot** [comment] 2016-04-28 00:54
Should be fixed in master.

Duplicate of #1824

**Closed by fguillot** 2016-04-28 00:54 UTC
Labels: bug
