### ISSUE TITLE
Blank dashboard when user added to a project

### ISSUE THREAD

**Issue by alimouzin** [fguillot/kanboard#553] opened 2015-01-27 13:06 UTC
Hello
I've installed kabanboard on my qnap nas.
After some issues with eAccelerator I have an other problem.
Once a user is put on a project the Dashboard page stays blank. 
If I remove the user for all the project he is part of, the Dashboard page displays properly.
I don't know what I could give you to help you help me. Just ask for what you need.

Arnaud

**Comment by mluepkes** [comment] 2015-01-27 18:39
Likely an error occuring and throwing a blank page. Set ```define('DEBUG', true);``` in ```config.php``` and check ```data/debug.log``` after reproducing the error.

**Comment by alimouzin** [comment] 2015-01-27 21:13
I'll do it tomorrow. It's on the LAN at work.

**Comment by alimouzin** [comment] 2015-01-28 10:15
So, I've activated the debug. In the log file you will find 2 actions : The first action is to add the admin to a project, the second one is to go to the dashboard: And in fact there is an error :

**[2015-01-28 10:08:53] [debug] SQLSTATE[HY000]: General error: 1 ambiguous column name: id**

The log file : http://pastebin.fr/38284

**Comment by alimouzin** [comment] 2015-01-28 10:31
I've done the same thing on a new database. The error is the same but that way I can give you the database if you want to check it : http://ovh.to/wgcxzGr

**Comment by fguillot** [comment] 2015-01-29 01:39
I pushed a fix in the development branch: https://github.com/fguillot/kanboard/commit/7703d0459ab33b8b5ca0e49410fe5b8b8962a61c

That should fix the problem. However, I cannot reproduce your issue, you have probably a very old version of sqlite. Do you know which version of sqlite and php is it?

**Comment by alimouzin** [comment] 2015-01-29 09:18
![image](https://cloud.githubusercontent.com/assets/10725203/5955075/389b2174-a79f-11e4-8976-947b754572fb.png)

pour php : PHP Version 5.3.29

le php info complet : https://hubic.com/pub/?ruid=aHR0cHM6Ly9sYjEuaHViaWMub3ZoLm5ldC92MS9BVVRIXzVkNzQxMzhlMWViODY0MDA1NmQ1MzUwZmQ5YTRiZTA2L2RlZmF1bHQvLm92aFB1Yi8xNDIyNTIzMDAxXzE0MjMzODcwMDE/dGVtcF91cmxfc2lnPWJjZWQyYWIwMzhhYjQwMTEyYTk1ZDA2YTZkYTBiNDQyN2Y3OTBhY2EmdGVtcF91cmxfZXhwaXJlcz0xNDIzMzg3MDAx

**Comment by alimouzin** [comment] 2015-01-29 10:31
And thanks a lot, It works very good know.

**Closed** 2015-01-30 02:41 UTC
Labels: bug
