### ISSUE TITLE
[Improvement] Configuration information into Settings page

### ISSUE THREAD

**Issue by orlov0562** [fguillot/kanboard#1999] opened 2016-03-12 12:22 UTC
Hello!

I suggest to append block with configuration information, that required to open the ticket.

This information:
```
- Kanboard version: v1.0.25-134-ga3994b1
- Database type and version: sqlite
- PHP version: PHP 5.5.9-1ubuntu4.14 
- OS: Ubuntu 14.04.3 LTS
- Browser: Chromium 48.0.2564.116 Ubuntu 15.10 (64-bit)
```

Kanboard can collect and show all this data right into Settings page, and users/admins can copy it into github tickets.

I mean something like:
```php
...
- PHP version: <?=phpversion()?><br>
- OS: <?=php_uname()?><br>
- Browser: <script>document.write(navigator.userAgent)</script><br>
```
give next
```
...
- PHP version: 7.0.3-5+deb.sury.org~wily+1
- OS: Linux PC 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64
- Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

**Comment by BlueTeck** [comment] 2016-03-12 12:36
duplicate of #1961

**Comment by fguillot** [comment] 2016-03-12 15:28
It's now available in the current master.

**Closed by fguillot** 2016-03-12 15:28 UTC
Labels: duplicate, improvement

**Comment by orlov0562** [comment] 2016-03-13 07:51
Thank you as usual for great product and prompt response!
