### ISSUE TITLE
Combined task board

### ISSUE THREAD

**Issue by crsaracco** [fguillot/kanboard#1216] opened 2015-09-10 16:29 UTC
As a single user of Kanboard without a team to collaborate with, I would like to have the following workflow:

 - Multiple projects, each with their own default color (see #1215)
 - A combined task board view, with all of the tasks from all of the projects shown on one page

This way I have the option of seeing only one project, or looking at all of the tasks as a whole that I have to work on.

**Comment by fguillot** [comment] 2015-09-17 02:38
As I understand it, it's a duplicate of #426

**Closed by fguillot** 2015-09-17 02:38 UTC
