### ISSUE TITLE
One kanboard for multiple projects

### ISSUE THREAD

**Issue by lasselicht** [fguillot/kanboard#767] opened 2015-04-05 20:35 UTC
We work on multiple projects at the same time and would like to be able to have one kanboard that has taks from all or selected projects.

**Comment by gulerin** [comment] 2015-05-12 16:00
I personally use swimming lanes to achieve this. A swimming lane per application (or in my case application version to be released).

**Comment by bluewindthings** [comment] 2015-05-18 08:20
Any progress on this? And btw: @gulerin how are you using swimlanes in this context? Did you find a way for showing tasks from more projects on the same swimlane?

**Comment by fronteerstrimm** [comment] 2015-05-18 08:37
We use categories to manage multiple projects in one board. The swimlane option makes it impossible to organise priorities over multiple projects. We will add tags in the future and make roles for our clients to just see their tags in our single board.

**Comment by gulerin** [comment] 2015-05-18 10:34
@bluewindthings: We do things really simple. We have a swimming lane per application version and don't share cards between lanes or applications. If there is a change that touches multiple applications we duplicate the card for each application. And although we have separate projects that contribute to an application version, our team considers an application version a project in its own right. So we focus on an application version and what is needed to be done there and not so much on the overarching projects. That is something the project manager can do, and she uses her own system of Excel sheets, Powerpoint files and Project documents. Currently only our devs use Kanboard. The main reason being a PEBKAC problem with the Project Managers :-)

**Comment by ftoulouse** [comment] 2015-05-19 14:30
Hi
I'm currently working on this feature. The goal of my team is to see all or selected projects in the same board while keeping the possibility of searching by user and dragging / droping task in the same project. This will be useful for our meetings.
I am going to propose this feature as soon as it will be developed (this is planed for the beginning of june)

**Comment by databigot** [comment] 2015-06-06 20:14
@ftoulouse: I have thought about this before.  The problem, as i see it is that different projects may have different columns defined.  Therefore it would make it difficult to show them on the same board.  My feeling about this, is that the projects that I would like to see on the same board, actually fall into the same "category" of project, and having common columns across them is a desirable thing.  So, my approach is to actually define the structure for a "category" of project: automatic actions, columns, etc.  Then any project of that "category" shares the same structure and can be shown on a common board.  
Anyway, those are my thoughts.  I have not tried building it yet.

**Comment by ftoulouse** [comment] 2015-06-07 22:11
@databigot : that's close to what I've done. In the feature I'm finishing, when you select some projects, they must share the same swimlanes and columns for being viewed together. I'm going to propose this feature in a few days.

**Comment by databigot** [comment] 2015-06-07 22:39
very nice @ftoulouse.  That was the one i forgot: "swimlanes must match".   I look forward to reading your proposed feature!
Another way to solve it would be to turn the current model on its head: make Boards the highest level entity, and then define the Projects within their Board.  The Board would define the "layout", having a defined set of Columns, Swimlanes, and automatic actions. A Project would be simpler, merely a "child" of only a single Board, and "inherit" the Colums, Swimlanes, unchangable!  may also inherit User set, and Automatic Actions.   
This design would limit certain things: one project on multiple boards, project specific logic -- but it closely fits my requirements.

Anyway, would probably require too much refactoring across the whole system.
-databigot

**Comment by fguillot** [comment] 2015-07-04 19:51
Duplicate of #426

**Closed by fguillot** 2015-07-04 19:51 UTC
Labels: duplicate, feature request
