### ISSUE TITLE
project title

### ISSUE THREAD

**Issue by esclkm** [fguillot/kanboard#1898] opened 2016-02-26 06:36 UTC
current version)))

when we have a lot of projects and entered into some task, we dont see PTOJECT TITLE -its makes developing hard

(another issue - put actions from left drop down menu to left bar)

**Comment by GDmac** [comment] 2016-02-26 07:25
+1 for "- add project title to task create/edit"

**Comment by fguillot** [comment] 2016-02-28 19:58
Yes, it's a duplicate of #1810

**Closed by fguillot** 2016-02-28 19:58 UTC
