### ISSUE TITLE
Bug: User Roles

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#2198] opened 2016-05-09 09:01 UTC
### Actual behaviour

I log in, and can't view any of the settings as my LDAP role has been altered from 'admin' to 'user' (which is correct, because as far as the *whole organisation* is concerned, that is my role).

### Expected behaviour

My role _for Kanboard_ is an administrator.  In fact, for us the default role for almost all users is administrator as they need some permissions that are only available to admin users.

I would suggest 2 changes:

1. Allow, in the settings, to disable the automatic synchronisation between LDAP and Kanboard
2. Allow me to add new roles / alter existing roles to produce a new role that will allow 'normal' users to be able to do most tasks (eg create a new public project), but not all.

**Comment by fguillot** [comment] 2016-05-10 00:51
Are you using LDAP group sync or not? only the basic LDAP authentication?

**Comment by AlgyTaylor** [comment] 2016-05-10 07:05
Here's the relevant part of config.php ....

```
// Enable LDAP authentication (false by default)
define('LDAP_AUTH', true);

// LDAP server hostname
define('LDAP_SERVER', '{server}');

// LDAP server port (389 by default)
define('LDAP_PORT', 389);

// By default, require certificate to be verified for ldaps:// style URL. Set to false to skip the verification.
define('LDAP_SSL_VERIFY', true);

// Enable LDAP START_TLS
define('LDAP_START_TLS', false);

// By default Kanboard lowercase the ldap username to avoid duplicate users (the database is case sensitive)
// Set to true if you want to preserve the case
define('LDAP_USERNAME_CASE_SENSITIVE', false);

// LDAP bind type: "anonymous", "user" (use the given user/password from the form) and "proxy" (a specific user to browse the LDAP directory)
define('LDAP_BIND_TYPE', 'proxy');

// LDAP username to connect with. null for anonymous bind (by default).
// Or for user bind type, you can use a pattern: %s@kanboard.local
define('LDAP_USERNAME', '{username}');

// LDAP password to connect with. null for anonymous bind (by default).
define('LDAP_PASSWORD', '{password}');

// LDAP DN for users
// Example for ActiveDirectory: CN=Users,DC=kanboard,DC=local
// Example for OpenLDAP: ou=People,dc=example,dc=com
define('LDAP_USER_BASE_DN', '{base dn}');

// LDAP pattern to use when searching for a user account
// Example for ActiveDirectory: '(&(objectClass=user)(sAMAccountName=%s))'
// Example for OpenLDAP: 'uid=%s'
define('LDAP_USER_FILTER', '(&(objectCategory=person)(sAMAccountName=%s))');

// LDAP attribute for username
// Example for ActiveDirectory: 'samaccountname'
// Example for OpenLDAP: 'uid'
define('LDAP_USER_ATTRIBUTE_USERNAME', 'samaccountname');

// LDAP attribute for user full name
// Example for ActiveDirectory: 'displayname'
// Example for OpenLDAP: 'cn'
define('LDAP_USER_ATTRIBUTE_FULLNAME', 'displayname');

// LDAP attribute for user email
define('LDAP_USER_ATTRIBUTE_EMAIL', 'mail');

// LDAP attribute to find groups in user profile
define('LDAP_USER_ATTRIBUTE_GROUPS', 'memberof');

// LDAP attribute for user avatar image: thumbnailPhoto or jpegPhoto
define('LDAP_USER_ATTRIBUTE_PHOTO', '');

// LDAP attribute for user language, example: 'preferredlanguage'
// Put an empty string to disable language sync
define('LDAP_USER_ATTRIBUTE_LANGUAGE', '');

// Allow automatic LDAP user creation
define('LDAP_USER_CREATION', false);

// LDAP DN for administrators
// Example: CN=Kanboard-Admins,CN=Users,DC=kanboard,DC=local
define('LDAP_GROUP_ADMIN_DN', '');

// LDAP DN for managers
// Example: CN=Kanboard Managers,CN=Users,DC=kanboard,DC=local
define('LDAP_GROUP_MANAGER_DN', '');

// Enable LDAP group provider for project permissions
// The end-user will be able to browse LDAP groups from the user interface and allow access to specified projects
define('LDAP_GROUP_PROVIDER', false);

// LDAP Base DN for groups
define('LDAP_GROUP_BASE_DN', '');

// LDAP group filter
// Example for ActiveDirectory: (&(objectClass=group)(sAMAccountName=%s*))
define('LDAP_GROUP_FILTER', '(&(objectClass=group)(sAMAccountName=%s*))');

// LDAP user group filter
// If this filter is configured, Kanboard will search user groups in LDAP_GROUP_BASE_DN with this filter
// Example for OpenLDAP: (&(objectClass=posixGroup)(memberUid=%s))
define('LDAP_GROUP_USER_FILTER', '');

// LDAP attribute for the group name
define('LDAP_GROUP_ATTRIBUTE_NAME', 'cn');
```

**Comment by AlgyTaylor** [comment] 2016-05-10 07:11
Hmmm, this is weird - I updated the plugins (#2199), tested it out, and it's working fine - but I've done nothing at the config, and had to manually change myself back from "user" to "admin" yesterday ... I am perplexed.

**Comment by rverchere** [comment] 2016-05-19 16:34
Hi, similar issue here.

Updated from 1.0.27 to 1.0.28, already use LDAP authentication (not group sync).
I updated the config file to have LDAP avatars, nothing more.

Before my user was admin, now I am a simple user.
When I log using a local admin account, I change my personal account from "user" to "admin".
log off and log in with my personal account, I'm still a "user".

I tried to add a LDAP admin group, update the configuration, same behaviour.

**Comment by fguillot** [comment] 2016-05-31 02:29
This issue is now fixed in the development branch. Thanks.

**Comment by fguillot** [comment] 2016-06-06 14:06
You can now use Kanboard 1.0.29, reopen this issue if necessary.

**Closed by fguillot** 2016-06-06 14:06 UTC
Labels: bug, Fixed in dev

**Comment by ariebarie** [comment] 2016-06-20 20:36
It seems that the issue is unfix on 1.0.30. Is there any workaround or new fix?

**Comment by fbartels** [comment] 2016-06-27 11:36
Hi, I today upgrade from 1.0.27 to 1.0.30 and am also seeing this behaviour. Users previously configured as admin (over the admin group) and now normal users.

@fguillot please reopen this one, or should I create a new issue?

**Comment by rverchere** [comment] 2016-06-27 14:07
Hi,  I confirm I still have the issue too.

**Comment by fguillot** [comment] 2016-06-28 03:18
@fbartels Open a new issue with absolutely all information needed to reproduce the problem (config, environment etc...) Thanks.
