### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 ambiguous column name: name

### ISSUE THREAD

**Issue by PipC** [fguillot/kanboard#2093] opened 2016-04-05 14:33 UTC
### Expected behaviour

When browse to "Project Management" there should be no ERROR.

### Actual behaviour
SQL error occurs see in debug.log;-
[2016-04-05 20:52:19] [debug] SELECT projects.*, users.username AS owner_username, users.name AS owner_name FROM "projects" LEFT JOI
N "users" ON "users"."id"="projects"."owner_id"  WHERE projects.id IN (?, ?)   ORDER BY "name" ASC  LIMIT 20  OFFSET 0
[2016-04-05 20:52:19] [debug] SQLSTATE[HY000]: General error: 1 ambiguous column name: name

Page displays the following:-
    Users overview
    Projects Gantt chart

Internal Error: SQL error: SQLSTATE[HY000]: General error: 1 ambiguous column name: name
Id 	Status 	▲ Project 	Start date 	End date 	Owner 	Users 	Columns

### Steps to reproduce

1. Try browse to "Project Management"
2. SQLSTATE[HY000]: General error: 1 ambiguous column name: name page display
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.27
- Database type and version:  sqlite 3.3.6
- PHP version: php.x86_64   5.1.6-45.el5_11
- OS: CentOS Linux 2.6.18-407.el5xen
- Browser: Firefox 45.0.1

**Comment by fguillot** [comment] 2016-04-28 00:39
Duplicate of #1976.

Which version of Centos do you have? 5.1?

**Closed** 2016-06-07 02:10 UTC
Labels: duplicate, unable to reproduce bug
