### ISSUE TITLE
Message "No columns in your project" in myqsl backend

### ISSUE THREAD

**Issue by Thieume** [fguillot/kanboard#1368] opened 2015-10-14 18:00 UTC
I created a totally fresh installation with MySQL backend. I create a new project, some columns (not the default one). And I want to show the columns to create tasks --> No columns in your project is shown. Impossible to create something.

**Comment by fguillot** [comment] 2015-10-17 01:36
How did you define your custom columns?

**Comment by Thieume** [comment] 2015-10-17 07:31
I create my project. I click on it from the dashboard.
I have the message "Il n'y a aucune colonne dans votre projet !"
Actions > Preferences > Columns : I have here 5 columns listed.

**Comment by fguillot** [comment] 2015-10-18 16:09
I cannot reproduce the issue even with a fresh install, did you disable all swimlanes? did you get any error during the execution of schema migrations?

**Comment by Thieume** [comment] 2015-10-19 13:47
Hum. The "problem" occurs when I rename the default swimlane. Before all is OK. After renaming, the columns disappear.
Little workaround : I create a new swimlane (will not be used after). For the default one a check box appears. I check the "show the default swimlane". I save, and I delete the newfresh swimlane.
After that, all is OK. Colums are back !

Is it a bug or a something wrong during the sqlite > mysql transfert ?

**Comment by fguillot** [comment] 2015-10-24 00:48
This is have been fixed in the master branch.

Thanks.

**Closed by fguillot** 2015-10-24 00:48 UTC
Labels: bug
