### ISSUE TITLE
Error 500 for summary export

### ISSUE THREAD

**Issue by thob** [fguillot/kanboard#1441] opened 2015-11-02 09:43 UTC
`?controller=export&action=summary&project_id=6&from=2015-10-01&to=2015-10-31` returns 500. All other exports just work.

I get this error in the log file
`[Mon Nov 02 10:41:14 2015] [error] [client 80.108.45.238] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Identifier "ProjectDailyColumnStats" is not defined.' in /is/htdocs/…kanboard/vendor/pimple/pimple/src/Pimple/Container.php:96\nStack trace:\n#0 /is/htdocs/…kanboard/app/Core/Base.php(124): Pimple\\Container-]offsetGet('ProjectDailyCol...')\n#1 /is/htdocs/…/app/Controller/Export.php(25): Core\\Base-]__get('ProjectDailyCol...')\n#2 /is/htdocs/…kanboard/app/Controller/Export.php(73): Controller\\Export-]common('ProjectDailyCol...', 'getAggregatedMe...', 'Zusammenfassung', 'summary', 'Export der t\\xC3\\xA4g...')\n#3 /is/htdocs/…/kanboard/app/Core/Router.php(225): Controller\\Export-]summary()\n#4 /is/htdocs/…/kanboard/index.php(5): Core\\Router-]dispatch('/kanboard/?cont...', 'controller=expo...')\n#5 {main}\n  thrown in /is/htdocs/…/kanboard/vendor/pimple/pimple/src/Pimple/Container.php on line 96`

Any idea what I'm missing?
Thanks

**Comment by fguillot** [comment] 2015-11-10 04:20
It's regression due to previous refactoring, need to be fixed.

**Comment by fguillot** [comment] 2015-11-14 20:38
This bug is fixed in master.

**Closed by fguillot** 2015-11-14 20:38 UTC
Labels: bug
