### ISSUE TITLE
Time Displayed on a task doesn't use system format

### ISSUE THREAD

**Issue by golharam** [fguillot/kanboard#1077] opened 2015-08-05 20:30 UTC
For example, on my system, the time is displayed as 4:20pm.  However in Kanboard, the time display on a task is 16:20 pm:

Created on August 5, 2015 at 14:20 PM
Last modified on August 5, 2015 at 16:20 PM
Created by xxx
Assigned to xxx
Column on the board: Work in progress (Models) since August 5, 2015 at 16:01 PM

**Comment by fguillot** [comment] 2015-08-06 00:17
Did you check the timezone configured in Kanboard? by default it's UTC. Don't forget that Kanboard use the server time and not your machine time.

**Comment by golharam** [comment] 2015-08-06 19:35
Yes, The Timezone is set to "America/New_York".  My server is my machine :)  I'm testing this on my linux box.

**Comment by fguillot** [comment] 2015-08-12 23:11
Sorry about my last comment I misread your issue. Yes, the time format is set to "24h format", that will be changed. It's a duplicate of ticket #982.

**Closed by fguillot** 2015-08-12 23:11 UTC
Labels: question
