### ISSUE TITLE
Unwanted "Due date" & "Start date" changes

### ISSUE THREAD

**Issue by aklipfel** [fguillot/kanboard#1902] opened 2016-02-27 17:47 UTC
### Expected behaviour

The date format is "dd/mm/yyyy"

### Actual behaviour

When we modify a task and save (even without modify it), the date "04/03/2016" became "03/04/2016"

### Steps to reproduce

1. Create a task with the due date "05/06/2016"
2. Modify it
3. Save the changes
4. The new due date is "06/05/2016"

The same problem affects the "Start Date"

### Configuration

- Kanboard version: 1.0.25
- Database type and version: MySQL 5.5
- PHP version: 
- OS: Windows / iOS
- Browser: I.E. / Safari Mobile / Firefox

**Comment by fguillot** [comment] 2016-02-28 19:52
Did you configure the date format in application settings?

**Comment by aklipfel** [comment] 2016-02-28 20:17
Yes, at the format dd/mm/yyyy

**Comment by gabimem** [comment] 2016-03-28 14:26
The problem is in the "getTimestamp" method of "DateParser" class, which does not use the format set by the user but uses the first valid format from the list of available formats.

One solution would be that in the field edit using the format "YYYY-MM-DD", and so even with the date picker

**Comment by aklipfel** [comment] 2016-03-28 16:47
Thank you for the answer.

Do you plan to correct that in a future release ?

Thank you

Arnaud

**Comment by damo2015** [comment] 2016-05-05 14:47
I am having the same issue. When I edit a task the date changes automatically - eg from 12/03/2016 to 03/12/2016

**Comment by letompouce** [comment] 2016-05-25 12:48
Same issue here. Kanboard 1.0.26, sqlite, php 5.4.45, OS/browser agnostic.

**Comment by fguillot** [comment] 2016-06-07 02:30
This issue have been fixed in Kanboard 1.0.29. Reopen this ticket if necessary.

**Closed by fguillot** 2016-06-07 02:30 UTC
Labels: bug, Fixed in dev

**Comment by ahummes** [comment] 2016-08-31 09:48
we are faceing same issue with Kanboard 1.0.32


Version: 1.0.32
PHP Version: 7.0.9
PHP SAPI: cgi-fcgi
OS Version: Windows NT 6.3
Datenbanktreiber: mysql
Datenbank Version: 5.7.14-log
