### ISSUE TITLE
Unreadable label in gantt chart when the name is too long.

### ISSUE THREAD

**Issue by mrfyx** [fguillot/kanboard#1163] opened 2015-09-01 15:24 UTC
![clipboard 1](https://cloud.githubusercontent.com/assets/7872032/9608367/56e9d836-50ce-11e5-8db4-253137ee4d7e.jpg)

There is a scroll bar on the text. See attached screenshot.

**Comment by sparkles645** [comment] 2015-09-01 15:44
Duplicate of #1153

**Closed** 2015-09-01 23:04 UTC
Labels: duplicate
