### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#1015] opened 2015-07-13 10:30 UTC
Hi,

This error message has been displayed to one of my fellow users in the subtask list on Kanboard:

![kanboard-dberr](https://cloud.githubusercontent.com/assets/1220211/8645630/08800b5c-2941-11e5-98c1-91216c3c4763.png)

I've not been able to recreate it myself, so not sure of the exact circumstances in which it appears. However, it happened when a subtask was changed to the 'todo' status, then the "start" button for time tracking was clicked - the screen refreshed and then the above error appeared.

**Comment by AlgyTaylor** [comment] 2015-07-13 10:31
Relevant subtask data from the DB:position
id; title; status; time_estimated; time_spent; task_id; user_id; 
249;"Find samples for ORF15 analysis";2;0;3;499;6;1
250;"Find samples which need BAMi files regenerated";2;0;4;499;6;2
251;"Regenerate BAMi files";1;0;0;499;6;3

**Comment by AlgyTaylor** [comment] 2015-07-13 10:40
subtask_time_tracking

id; user_id; subtask_id; start; end; time_spent
215;6;249;1436520846;1436520887;0
216;6;250;1436520889;1436528574;2.25
217;6;250;1436531076;1436537614;1.75
218;6;251;1436541501;0;0
219;6;251;1436541503;0;0

**Comment by fguillot** [comment] 2015-07-14 01:17
I tried multiple times with the data you provided but I was unable to reproduce the error.

- What version of Kanboard are you using, 1.0.16 I suppose?
- What database do you use Sqlite, Postgres or Mysql?
- Apparently you installed Kanboard on a windows server, what version of php do you use?

**Comment by AlgyTaylor** [comment] 2015-07-14 07:09
Hi,

Yeah, it's version 1.0.16. I'm using Windows Server 2008 / PostgreSQL 9.4 / Apache 2.0 / PHP 5.5.15

Is there any other data that might help?  If it's any use, the error was only appearing for the user the timings were linked to (user_id = 6), not anyone else.

**Comment by fguillot** [comment] 2015-07-25 21:34
I finally reproduced the bug and it's now fixed.

There were 2 entries in the table for the same subtask and user, and Postgres was the only database to complaint with the error "more than one row returned by a subquery used as an expression". Postgres is definitively stricter and better than other databases.

Thanks to report this issue!

**Closed by fguillot** 2015-07-25 21:34 UTC
Labels: bug
