### ISSUE TITLE
Provide the ability to add labels, tags or icons in Tasks

### ISSUE THREAD

**Issue by menegrete** [fguillot/kanboard#2245] opened 2016-05-19 11:53 UTC
### Expected behaviour

Option to add labels, tags or icons in Tasks to identify or categorize.

### Actual behaviour

Currently there is no such option in Tasks.

### Configuration

- Kanboard version: 1.0.26

**Comment by BlueTeck** [comment] 2016-05-19 12:06
duplicate of #262 and see #646

**Comment by menegrete** [comment] 2016-05-19 13:04
+1 for this

**Closed** 2016-05-26 03:15 UTC
Labels: duplicate
