### ISSUE TITLE
Gantt Charts

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#725] opened 2015-03-18 10:43 UTC
Hi,

Is it possible to add a Gantt chart (http://en.wikipedia.org/wiki/Gantt_chart)-type functionality to the Kanboard dashboard, or perhaps to one of the project or analytics pages?  It'd be incredibly helpful :)

Thanks,
Algy

**Comment by valessiobrito** [comment] 2015-04-26 14:56
Gantt charts the a project using JQuery: http://taitems.github.io/jQuery.Gantt/

**Comment by fguillot** [comment] 2015-07-04 19:50
Duplicate of #832

**Closed by fguillot** 2015-07-04 19:50 UTC
Labels: duplicate, feature request

**Comment by fguillot** [comment] 2015-08-14 21:33
Gantt chart is available in the dev version, see https://github.com/fguillot/kanboard/blob/master/docs/gantt-chart.markdown
