### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by djsensui** [fguillot/kanboard#1761] opened 2016-02-02 08:57 UTC
It is possible to pull user picture via Active Directory? 
Photo attribute : thumbnailPhoto / jpegPhoto

Thanks.

**Comment by fguillot** [comment] 2016-02-03 01:08
It's planned when avatar images will be implemented correctly.

**Comment by angystardust** [comment] 2016-02-04 14:20
I think this can be marked as a duplicate of #126

**Comment by NinjaPewPew** [comment] 2016-02-07 10:23
:+1:

**Comment by djsensui** [comment] 2016-03-28 05:37
Hi, 
Loving the 1.0.27 specially that you can now upload profile pictures. 

Hoping for the future release that the avatar images can be pulled thru AD. 
(Photo attribute : thumbnailPhoto / jpegPhoto)

It is possible to disable editing profile by non-admin?

**Comment by rverchere** [comment] 2016-04-08 09:20
+1, retrieving jpegPhoto from LDAP should be great!

**Comment by fguillot** [comment] 2016-05-07 17:13
This feature is now available in the development branch: https://github.com/fguillot/kanboard/blob/master/doc/ldap-profile-picture.markdown

**Closed by fguillot** 2016-05-07 17:13 UTC
Labels: feature request
