### ISSUE TITLE
Trouble upgrading from 1.0.24 to 1.0.25

### ISSUE THREAD

**Issue by PBrn46** [fguillot/kanboard#1815] opened 2016-02-10 01:42 UTC
Hello,

When I am upgrading from 1.0.24 to 1.0.25, I am getting the following error with an existing sqlite database (with debug mode on):

`Internal Error: SQL error: SQLSTATE[HY000]: General error: 1 ambiguous column name: name`

This is when trying to load the landing page after login, while generating the Project column (the rest of the page generation halts).

However, starting a new deployment has no issues with the same configuration file.

The tail of the debug log is as follows:
```

[2016-02-09 17:36:11] [debug] ###############################################
[2016-02-09 17:36:51] [debug] Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
[2016-02-09 17:36:51] [debug] Rendering app/filters_helper in 0.00080990791320801s, total=0.00080990791320801
[2016-02-09 17:36:51] [debug] SELECT "option", "value" FROM "settings"
[2016-02-09 17:36:51] [debug] QUERY_DURATION=0.0023648738861084 ALL_QUERIES_DURATION=0.0023648738861084
[2016-02-09 17:36:51] [debug] SELECT projects.id, projects.name FROM "projects" LEFT JOIN "project_has_users" ON "project_has_users"."project_id"="projects"."id"  WHERE (project_has_users.user_id = ? OR projects.is_everybody_allowed = ?) AND projects.is_active IN (?)
[2016-02-09 17:36:51] [debug] QUERY_DURATION=0.0003211498260498 ALL_QUERIES_DURATION=0.0026860237121582
[2016-02-09 17:36:51] [debug] SELECT projects.id, projects.name FROM "projects" LEFT JOIN "project_has_groups" ON "project_has_groups"."project_id"="projects"."id" LEFT JOIN "group_has_users" ON "group_has_users"."group_id"="project_has_groups"."group_id"  WHERE group_has_users.user_id = ? AND projects.is_active IN (?)
[2016-02-09 17:36:51] [debug] QUERY_DURATION=0.0002439022064209 ALL_QUERIES_DURATION=0.0029299259185791
[2016-02-09 17:36:51] [debug] SELECT * FROM "actions"   WHERE "project_id" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
[2016-02-09 17:36:51] [debug] QUERY_DURATION=0.00011396408081055 ALL_QUERIES_DURATION=0.0030438899993896
[2016-02-09 17:36:51] [debug] SELECT * FROM "action_has_params"
[2016-02-09 17:36:51] [debug] QUERY_DURATION=7.7009201049805E-5 ALL_QUERIES_DURATION=0.0031208992004395
[2016-02-09 17:36:51] [debug] SELECT 1 FROM "users"  WHERE "id" = ?
[2016-02-09 17:36:51] [debug] QUERY_DURATION=8.1062316894531E-5 ALL_QUERIES_DURATION=0.003201961517334
[2016-02-09 17:36:51] [debug] SELECT * FROM "users"   WHERE "id" = ?    LIMIT 1
[2016-02-09 17:36:51] [debug] QUERY_DURATION=0.00014901161193848 ALL_QUERIES_DURATION=0.0033509731292725
[2016-02-09 17:36:51] [debug] SELECT projects.id, projects.name FROM "projects" LEFT JOIN "project_has_users" ON "project_has_users"."project_id"="projects"."id"  WHERE (project_has_users.user_id = ? OR projects.is_everybody_allowed = ?) AND projects.is_active IN (?)
[2016-02-09 17:36:51] [debug] QUERY_DURATION=0.00022101402282715 ALL_QUERIES_DURATION=0.0035719871520996
[2016-02-09 17:36:51] [debug] SELECT projects.id, projects.name FROM "projects" LEFT JOIN "project_has_groups" ON "project_has_groups"."project_id"="projects"."id" LEFT JOIN "group_has_users" ON "group_has_users"."group_id"="project_has_groups"."group_id"  WHERE group_has_users.user_id = ? AND projects.is_active IN (?)
[2016-02-09 17:36:51] [debug] QUERY_DURATION=0.00024104118347168 ALL_QUERIES_DURATION=0.0038130283355713
[2016-02-09 17:36:51] [debug] SELECT COUNT(*) FROM "projects" LEFT JOIN "users" ON "users"."id"="projects"."owner_id" WHERE projects.id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
[2016-02-09 17:36:51] [debug] QUERY_DURATION=0.00028300285339355 ALL_QUERIES_DURATION=0.0040960311889648
[2016-02-09 17:36:51] [debug] SELECT COUNT(*) FROM "tasks" LEFT JOIN "projects" ON "projects"."id"="tasks"."project_id" WHERE tasks.owner_id = ? AND tasks.is_active = ? AND projects.is_active = ?
[2016-02-09 17:36:51] [debug] QUERY_DURATION=0.00031280517578125 ALL_QUERIES_DURATION=0.0044088363647461
[2016-02-09 17:36:51] [debug] SELECT COUNT(*) FROM "subtasks" LEFT JOIN "tasks" ON "tasks"."id"="subtasks"."task_id" LEFT JOIN "projects" ON "projects"."id"="tasks"."project_id" WHERE "user_id" = ? AND projects.is_active = ? AND subtasks.status IN (?, ?)
[2016-02-09 17:36:51] [debug] QUERY_DURATION=0.00029182434082031 ALL_QUERIES_DURATION=0.0047006607055664
[2016-02-09 17:36:51] [debug] SELECT projects.*, users.username AS owner_username, users.name AS owner_name FROM "projects" LEFT JOIN "users" ON "users"."id"="projects"."owner_id"  WHERE projects.id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)   ORDER BY "name" ASC  LIMIT 10  OFFSET 0
[2016-02-09 17:36:51] [debug] SQLSTATE[HY000]: General error: 1 ambiguous column name: name
[2016-02-09 17:36:51] [debug] SQL_QUERIES=12
[2016-02-09 17:36:51] [debug] RENDERING=0.067270994186401
[2016-02-09 17:36:51] [debug] MEMORY=2.27M
[2016-02-09 17:36:51] [debug] URI=/tasks-1.0.25/
[2016-02-09 17:36:51] [debug] ###############################################

```

**Comment by PBrn46** [comment] 2016-02-10 23:43
From the previous post, I am thinking the following statement is causing the error because of the table users and able projects both having a column 'name'.
`[2016-02-09 17:36:51] [debug] SELECT projects.*, users.username AS owner_username, users.name AS owner_name FROM "projects" LEFT JOIN "users" ON "users"."id"="projects"."owner_id"  WHERE projects.id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)   ORDER BY "name" ASC  LIMIT 10  OFFSET 0`

**Comment by bdrayer** [comment] 2016-02-11 11:21
Hi, I also add this problem, ... But forget to fill a bug for it there.

In my case I comment the line 40 of /PATH_TO_YOUR_KANBOARD_INSTALLATION/app/Schema/Mysql.php and it worked. It blocked because the column is already existing.

```
function version_102(PDO $pdo)
{
    //$pdo->exec("ALTER TABLE projects ADD COLUMN owner_id INT DEFAULT 0");
}
```

**Comment by fguillot** [comment] 2016-04-28 00:39
Duplicate of #2093 and #1976

**Closed by fguillot** 2016-04-28 00:39 UTC
Labels: need to investigate
