### ISSUE TITLE
Board selector when everybody is allowed

### ISSUE THREAD

**Issue by Pybou** [fguillot/kanboard#729] opened 2015-03-18 16:33 UTC
Hello,

First of all, thanks for this fantastic project, you are doing a very good job!

I have a question, I don't really know if it's a bug or if it's normal but I don't understand why the board selector doesn't appear for everybody when we checked "Everybody is allowed" in project settings.

Thanks a lot

**Comment by BlueTeck** [comment] 2015-03-18 16:40
Duplicate #722

**Comment by BlueTeck** [comment] 2015-03-18 16:41
And duplicate of 698

**Comment by BlueTeck** [comment] 2015-03-18 16:41
#698

**Comment by Pybou** [comment] 2015-03-18 22:06
Ok, sorry for that ;-)

Thanks

**Comment by fguillot** [comment] 2015-03-21 22:18
It's fixed in the master branch.

**Comment by Pybou** [comment] 2015-03-23 09:42
Works perfectly ;-)
Cheers

**Closed** 2015-04-06 23:46 UTC
Labels: bug
