### ISSUE TITLE
Adding screenshots by # dropdown menu in board does not work in all browsers

### ISSUE THREAD

**Issue by Chaosmeister** [fguillot/kanboard#1026] opened 2015-07-15 10:13 UTC
![image](https://cloud.githubusercontent.com/assets/13346344/8696135/26122db2-2aea-11e5-88bd-c8ff532edf85.png)

In Chrome this works as expected.
Neither Firefox nor Internet Explorer fill the box from the clipboard 
[edit] if I clicked into the box.

![image](https://cloud.githubusercontent.com/assets/13346344/8696039/7d3ed122-2ae9-11e5-8937-ad82930476ed.png)

Additionally, after clicking on the "Add a screenshot" button, the screen scrolls down to the bottom of the board and every buttonpress (mouse & keyboard) also results in scrolling to the bottom of the board until the page is reloaded. This happened in all tested browsers.
This does not happen with any other menuitem in the dropdownmenu.

**Comment by Chaosmeister** [comment] 2015-07-15 13:45
Also in some cases, the overlay can't be exited with the `esc`-key.

**Comment by wiLLow86** [comment] 2015-07-15 14:23
For me it works perfect with FireFox

**Comment by Chaosmeister** [comment] 2015-07-15 14:27
I'm using the latest Firefox:
![image](https://cloud.githubusercontent.com/assets/13346344/8700776/2dfe20d4-2b0e-11e5-898c-4d134bf0ef9f.png)

Pasting the screenshot into Paint or in Chrome works without any problems.

**Comment by wiLLow86** [comment] 2015-07-15 14:36
I'm using 39.0 too.
Do you take the Screenshot with ALTGR+PRINT or only PRINT?
For me both is working but it take 2-3 seconds after pasting with STRG+V

**Comment by Chaosmeister** [comment] 2015-07-15 14:46
I tried both as well. Both without result.

Our Kanboard runs on IIS if that's somehow relevant.

**Comment by fguillot** [comment] 2015-07-16 00:23
I tried with Chrome and Firefox 39 on Mac OS, that works for me, I will try later with Windows.

**Comment by Chaosmeister** [comment] 2015-07-16 07:42
I tried to isolate the issue some more:
Clicking on the "Add a screenshot" button - then clicking into the box makes Firefox not accepting the image.
If I don't click into the box, just clicking the button and then strg+v, it works in Firefox. 

Regarding my other find, should I create a separate issue? (scrolling to the bottom of the board)

**Comment by fguillot** [comment] 2015-07-18 19:55
I reproduced both issues and it's fixed now in the master branch.

This feature is hack around the contentEditable element, so it's not perfect, that still a workaround.

**Closed by fguillot** 2015-07-18 19:55 UTC
Labels: bug
