### ISSUE TITLE
LDAP_GROUP_ADMIN_DN is not creating admins on login.

### ISSUE THREAD

**Issue by austinbarrington** [fguillot/kanboard#1788] opened 2016-02-06 14:46 UTC
Hello,

I have set `LDAP_GROUP_ADMIN_DN` & `LDAP_GROUP_MANAGER_DN` in the config file to separate groups in our LDAP domain. When I login using one of these members their permissions are still just user and not Admin or Manager.

Looking at your debug log doesn't really tell me much as to why it is not making them admins.

Do you have any suggestions as to what I need to look for to find the cause for this?

**Comment by austinbarrington** [comment] 2016-02-12 17:41
After some digging I found it here:
file: /app/Core/Ldap/User.php

```
/**
     * Build user profile
     *
     * @access protected
     * @return LdapUserProvider
     */
    protected function build()
    {
        $entry = $this->query->getEntries()->getFirstEntry();
        $role = Role::APP_USER;
        if ($entry->hasValue($this->getAttributeGroup(), $this->getGroupAdminDn())) {
            $role = Role::APP_ADMIN;
        } elseif ($entry->hasValue($this->getAttributeGroup(), $this->getGroupManagerDn())) {
            $role = Role::APP_MANAGER;
        }
        return new LdapUserProvider(
            $entry->getDn(),
            $entry->getFirstValue($this->getAttributeUsername()),
            $entry->getFirstValue($this->getAttributeName()),
            $entry->getFirstValue($this->getAttributeEmail()),
            $role,
            $entry->getAll($this->getAttributeGroup())
        );
    }
```
`$entry` returns just the user and not attributed groups. Hence why the ldapgroups are not found within it.
We are using OpenLDAP and not active directory. In our OpenLDAP we don't have the memberof function as well.

**Comment by fguillot** [comment] 2016-02-24 02:05
Closing, related to #1652

**Comment by MarcoArdito** [comment] 2016-03-31 12:46
Hi, I am using Active directory, but I have the same problem: members of the specified group are not assigned to admins or managers, they are jsut leaved as regular users... (on  1.0.27)

using windows tool ldp I can browse the ad/ldap and see that memberOf attribute is there and reflects the real group mambership...

**Comment by MarcoArdito** [comment] 2016-03-31 13:26
I also found that when the user is **created** it gets admin or manager rols based on its ad/ldap groups, but this does not **change** if the ad/ldap groups change **after**. 

eg: if at first login the user is not in the LDAP_GROUP_ADMIN_DN or LDAP_GROUP_MANAGER_DN group, its role is "user". But then if in the ad/ldap he becomes member of the right group, its role is not changed... this may be by design, perhaps...?

**Comment by fguillot** [comment] 2016-05-08 17:51
Latest Kanboard now supports ActiveDirectory, OpenLDAP with memberOf, groupOfNames and Posix Groups.

There are 4 different examples on the website to help you to configure that: https://kanboard.net/documentation/ldap-configuration-examples

@MarcoArdito the role/group sync have been improved also in latest kanboard

**Closed by fguillot** 2016-05-08 17:51 UTC
Labels: triage
